### ISSUE TITLE
Update essay 7 .md, references.yml, and figures.yml based on revised text from author. 

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/egypt-classical-world#45]
@audreywarne Thank you so much for chatting with me today and for signing up to do all this work. Below is the list of changes that need to be made by Friday. For big questions, please respond in this issue. For small things, feel free to shoot me a quick email. 

- [x] Replace Essay 7 text with converted text (but save original essay 7 text because you will need that as a guide)
- [x] Add #'s to create section headings (use original essay 7 as a guide)
- [x] Clean up tables following Greg’s formatting
    - [x] Headings can be cut and pasted (use original essay 7 as a guide)
    - [x] But content should follow Greg’s pattern
- [x] Clean up asterisks in transliterated text (look at original essay as guide)  
For example: 
`  ↓→ ***\@r Hwn n\<x\>t(?) \<nb.ty\> iTi*** ˹***m sxm***˺ ***bik nbw*** ˹***wsr rnp.w(t)***˺ ***aA nxt \<nsw.t bi.ty\>*** ˹***AW***˺***&QR&R K%R% nsw.t bi.ty &***˹***M***˺***\[&\]IN% anx D.t xbi in(.w) m tA.wy xAs.wt m ntyy.w r iy.t=f n.t Xnw \[!r\]***˹***m***˺ ` 
should be 
`| ↓→ ***\@r Hwn n\<x>t(?) \<nb.ty> iTi ˹m sxm˺ bik nbw ˹wsr rnp.w(t)˺ aA nxt \<nsw.t bi.ty> ˹AW˺&QR&R K%R% nsw.t bi.ty &˹M˺\[&\]IN% anx D.t xbi in(.w) m tA.wy xAs.wt m ntyy.w r iy.t=f n.t Xnw \[!r\]˹m˺*** |`
- [x] Search for {.smallcaps} and replace curly brackets with span (use original essay 7 as a guide)
For example: `[Domitian]{.smallcaps}` should be `<span class="smallcaps">Domitian</span>`
- [x] Search for {.ul} and replace curly brackets with span (use original essay 7 as a guide)
For example: `[the King of Upper and Lower Egypt]{.ul}` should be `<span class="underline">the King of Upper and Lower Egypt</span>`
- [x] Search for instances of `![](media/....}` images and follow Greg’s formatting 
For example: `![](media/image16.emf){width="0.20833333333333334in" height="0.19444444444444445in"}` should be `![](/img/figures/essay-07-inline/image16.svg)`
- [x] Use regex to wrap author date references in curly brackets (see issue #14) 
- [x] Convert bibliography with regex and replace in `references.yml` (issue #14)
    - [x] Keep original version of `references.yml`
- [x] Correct formatting of hieroglyph in Spalinger 2015 in `references.yml` (issue #32)
    - [x] Use original `references.yml` text as a guide
- [x] Use regex to convert author date to `q-cite` shortcode (issue #27)
- [x] Correct any `q-cite` errors where the `q-cite` shortcode does not match the `references.yml`
    - [x] Keep track of any broken links you're not sure how to fix
- [x] Copy and paste q-figure shortcodes from old version 
For example: 

`{FIG. 10 + caption (orthophoto of A/1)}`
`{FIG. 11 + caption (photo of B/1)}`
`{FIG. 12 + caption (A/1 and B/1 facsimile)}`
`{FIG. 13 + caption (side 1 hieroglyphs)}` 

should be 

`{{< q-figure-group grid="2" id="fig-7-10, fig-7-11" class="pdf-two-column" >}}`
`{{< q-figure-group grid="2" id="fig-7-12, fig-7-13" class="pdf-two-column" >}}`

- [x] Replace captions text for all essay 7 captions in the `figures.yml`

Here are the FINAL markdown files you should use to make these changes (this is the same as what I previously sent you). 

[11_Prada essay_final_tracked_CLEAN_13dec21_GA.md](https://github.com/thegetty/egypt-classical-world/files/7707570/11_Prada.essay_final_tracked_CLEAN_13dec21_GA.md)
[11b_Prada bibliography_final_tracked_CLEAN_13dec21.md](https://github.com/thegetty/egypt-classical-world/files/7707571/11b_Prada.bibliography_final_tracked_CLEAN_13dec21.md)
[11a_Prada captions_final_tracked_CLEAN_13dec21.md](https://github.com/thegetty/egypt-classical-world/files/7707583/11a_Prada.captions_final_tracked_CLEAN_13dec21.md)
